{% set version = "1.4.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ucscxenatools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/UCSCXenaTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/UCSCXenaTools/UCSCXenaTools_{{ version }}.tar.gz
  sha256: 473507e60e2706c349eb20f925d60c1472feb1052f4804cd3c86472d8dbe1970

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-digest
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-magrittr
    - r-readr
    - r-rlang
  run:
    - r-base
    - r-digest
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-magrittr
    - r-readr
    - r-rlang

test:
  commands:
    - $R -e "library('UCSCXenaTools')"           # [not win]
    - "\"%R%\" -e \"library('UCSCXenaTools')\""  # [win]

about:
  home: https://docs.ropensci.org/UCSCXenaTools/, https://github.com/ropensci/UCSCXenaTools
  license: GPL-3.0-only
  summary: Download and explore datasets from UCSC Xena data hubs, which are a collection of UCSC-hosted public databases such as TCGA, ICGC, TARGET, GTEx, CCLE, and others. Databases are normalized so they can be combined, linked, filtered, explored and downloaded.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ShixiangWang
